### ISSUE TITLE
Pre-trained models without 4x96 multi-crops? 

### ISSUE THREAD

**Issue by frank-xwang** [facebookresearch/swav#3]
Hi, Thanks for your excellent work! Is it possible for you to release pre-trained models and results without 4x96 crops? Thank you so much!

**Comment by mathildecaron31** [comment]
Hi, thanks for your interest in our work ! I've included some models trained with only two 224x224 crops during 400 epochs. See commit: https://github.com/facebookresearch/swav/commit/2d898a425f2951eafb0c87156bcaf9270f97caf0

**Comment by frank-xwang** [comment]
Hi, thanks for your reply. Can I know the performance during 200 epochs? Thank you for your excellent work and code release.

**Comment by mathildecaron31** [comment]
I'm sorry, I have not run it for 200 epochs.

If this is really critical for you, I can try to find the bandwidth to run it. Let me know

**Comment by frank-xwang** [comment]
Hi, due to the limited computing resources of the academic groups, it will be easier for us to reproduce your results with less time cost. I will appreciate it if you could provide the performance of 200 epochs. Thanks a lot.

**Comment by DonkeyShot21** [comment]
Hi, @mathildecaron31 did you happen to have the time and resources to run 200 epochs with batch size 256 and without multi-crop? I am asking because this seems a standard configuration in the literature but it is missing both in the paper and the repo. I think this would help a lot of less lucky researchers (in terms of resource availability).
