### ISSUE TITLE
Code for implementing SeLa-v2?

### ISSUE THREAD

**Issue by wenjiaXu** [facebookresearch/swav#59]
Hello, would you mind providing the implementation code of SeLa-v2? Thanks a lot for your help!

**Comment by mathildecaron31** [comment]
Hi @wenjiaXu 

Thanks a lot for your interest.

That's something I have not planned to do, I'll let you know if I find the bandwidth to do it.

It should not be too difficult to integrate starting from the `main_deepclusterv2.py` file since the two approaches are very similar. You would just need to replace the assignments given by k-means by assignments given by Sinkhorn-Knop basically. And no need to update the prototypes with centroids since in this case they are learned with SGD (like in SwAV). Also, feel free to propose a pull request.
