### ISSUE TITLE
Warning for no unused parameters

### ISSUE THREAD

**Issue by robbiejones96** [facebookresearch/swav#63]
Hi there, thanks so much for sharing your implementation with the community! At the beginning of training, I'm seeing this warning

```
[W reducer.cpp:1050] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters. This flag results in an
extra traversal of the autograd graph every iteration, which can adversely affect performance. If your model indeed never has any unused parameters, consider t
urning this flag off. Note that this warning may be a false positive your model has flow control causing later iterations to have unused parameters. (function
operator())
```

I see that `find_unused_parameters` is explicitly set to `True` in the line

```
model = nn.parallel.DistributedDataParallel(
        model,
        device_ids=[args.gpu_to_work_on],
        find_unused_parameters=True,
    )
```

Two questions:
1) Are there indeed unused parameters that aren't detected on the first pass?
2) If not, do you know if there would be a noticeable performance improvement in setting `find_unused_parameters` to `False`?

Thanks so much!

**Comment by mathildecaron31** [comment]
Hi @robbiejones96 

Thanks a lot for your interest in this work.

1. There are no unused parameters in the algorithm, so we should set this flag off as per PyTorch recommendation. Thanks for flagging it. I think I set this to `true` by default because in previous iterations or experimentations I needed that feature and it just stayed in my code after that. Do you want to do a PR to remove it ? Otherwise I can just do a new commit.

2. I don't know. My guess would be that it does make any difference but I have not tested. If you want to benchmark this, that would be very nice :).
