### ISSUE TITLE
Changes to standard ResNet

### ISSUE THREAD

**Issue by kshen6** [facebookresearch/swav#81]
Hi authors,
Thanks for making this repository public, it's excellent and easy to use! I had one question about the update you made to the resnet50.py code on line 157. Is there somewhere in the paper that the extra padding is discussed (if there is, I couldn't find it), or can you explain why it is necessary? I am trying to implement SwAV for DenseNets and am wondering if the padding should be added there as well. Thanks so much in advance.

**Comment by mathildecaron31** [comment]
Hi @kshen6 

With the padding the implementation is strictly equivalent to that of torchvision since the padding in the first conv is 2 instead of 3 in torchvision.

The padding layer is there because of previous experiments that I did and that required it. You could very well remove the padding layer and use padding=3 instead of padding=2 here: https://github.com/facebookresearch/swav/blob/5e073db0cc69dea22aa75e92bfdd75011e888f28/src/resnet50.py#L173-L177

**Comment by kshen6** [comment]
Thank you for the prompt and helpful reply. Closing this thread!
